/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas.reportes;

/**
 *
 * @author Noe
 */
public class PanelSeleccionarReporte extends javax.swing.JPanel {

    /**
     * Creates new form PanelSeleccionarReporte
     */
    public PanelSeleccionarReporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxReporte = new javax.swing.JComboBox();
        botonGenerarReporte = new javax.swing.JButton();

        comboBoxReporte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Empleados", "Proveedor", "Articulos Vendidos", "Ventas" }));
        comboBoxReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxReporteActionPerformed(evt);
            }
        });

        botonGenerarReporte.setText("GenerarReporte");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(comboBoxReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(botonGenerarReporte)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGenerarReporte))
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGenerarReporte;
    private javax.swing.JComboBox comboBoxReporte;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the botonGenerarReporte
     */
    public javax.swing.JButton getBotonGenerarReporte() {
        return botonGenerarReporte;
    }

    /**
     * @param botonGenerarReporte the botonGenerarReporte to set
     */
    public void setBotonGenerarReporte(javax.swing.JButton botonGenerarReporte) {
        this.botonGenerarReporte = botonGenerarReporte;
    }

  
    /**
     * @return the comboBoxReporte
     */
    public javax.swing.JComboBox getComboBoxReporte() {
        return comboBoxReporte;
    }

    /**
     * @param comboBoxReporte the comboBoxReporte to set
     */
    public void setComboBoxReporte(javax.swing.JComboBox comboBoxReporte) {
        this.comboBoxReporte = comboBoxReporte;
    }
   
}
