/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas.reportes;

/**
 *
 * @author Noe
 */
public class PanelSeleccionarReporte extends javax.swing.JPanel {

    /**
     * Creates new form PanelSeleccionarReporte
     */
    public PanelSeleccionarReporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxReporte = new javax.swing.JComboBox();
        botonGenerarReporte = new javax.swing.JButton();
        etiquetaTipoReporte = new javax.swing.JLabel();
        etiquetaInicial = new javax.swing.JLabel();
        etiquetaFechaFinal = new javax.swing.JLabel();
        campoFechaInicial = new javax.swing.JTextField();
        campoFechaFinal = new javax.swing.JTextField();

        comboBoxReporte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Empleados", "Proveedor", "Articulos Vendidos", "Ventas" }));
        comboBoxReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxReporteActionPerformed(evt);
            }
        });

        botonGenerarReporte.setText("GenerarReporte");

        etiquetaTipoReporte.setText("Tipo Reporte");

        etiquetaInicial.setText("Fecha Inicial (dd-mm-yyyy)");

        etiquetaFechaFinal.setText("Fecha Final (dd-mm-yyyy)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaTipoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaInicial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botonGenerarReporte)
                                .addGap(62, 62, 62))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etiquetaFechaFinal))
                                .addGap(43, 43, 43))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(etiquetaTipoReporte)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGenerarReporte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaInicial)
                    .addComponent(etiquetaFechaFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGenerarReporte;
    private javax.swing.JTextField campoFechaFinal;
    private javax.swing.JTextField campoFechaInicial;
    private javax.swing.JComboBox comboBoxReporte;
    private javax.swing.JLabel etiquetaFechaFinal;
    private javax.swing.JLabel etiquetaInicial;
    private javax.swing.JLabel etiquetaTipoReporte;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the botonGenerarReporte
     */
    public javax.swing.JButton getBotonGenerarReporte() {
        return botonGenerarReporte;
    }

    /**
     * @param botonGenerarReporte the botonGenerarReporte to set
     */
    public void setBotonGenerarReporte(javax.swing.JButton botonGenerarReporte) {
        this.botonGenerarReporte = botonGenerarReporte;
    }

  
    /**
     * @return the comboBoxReporte
     */
    public javax.swing.JComboBox getComboBoxReporte() {
        return comboBoxReporte;
    }

    /**
     * @param comboBoxReporte the comboBoxReporte to set
     */
    public void setComboBoxReporte(javax.swing.JComboBox comboBoxReporte) {
        this.comboBoxReporte = comboBoxReporte;
    }

    /**
     * @return the campoFechaFinal
     */
    public javax.swing.JTextField getCampoFechaFinal() {
        return campoFechaFinal;
    }

    /**
     * @param campoFechaFinal the campoFechaFinal to set
     */
    public void setCampoFechaFinal(javax.swing.JTextField campoFechaFinal) {
        this.campoFechaFinal = campoFechaFinal;
    }

    /**
     * @return the campoFechaInicial
     */
    public javax.swing.JTextField getCampoFechaInicial() {
        return campoFechaInicial;
    }

    /**
     * @param campoFechaInicial the campoFechaInicial to set
     */
    public void setCampoFechaInicial(javax.swing.JTextField campoFechaInicial) {
        this.campoFechaInicial = campoFechaInicial;
    }

  
    
    
   
}
