/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas.reportes;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rodrigopeniche
 */
public class PanelVerReporte extends javax.swing.JPanel {
    
    private VentanaReportes ventanaReportes;
    private DefaultTableModel contenidoTablaReporte;
    /**
     * Creates new form PanelVerProveedores
     * @param ventanaPrincipal
     */
    public PanelVerReporte( ) {
        initComponents( );
                
//        contenidoTablaReporte = new DefaultTableModel( );
//        String camposTabla[] = new String[]{"Clave", "Nombre", "Teléfono", "Dirección"};
//       contenidoTablaReporte.setColumnIdentifiers( camposTabla );
//        tablaReporte.setModel( contenidoTablaReporte );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloReporte = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReporte = new javax.swing.JTable();

        tablaReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaReporte);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(tituloReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(tituloReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaReporte;
    private javax.swing.JLabel tituloReporte;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the ventanaProveedores
     */
    public VentanaReportes getVentanaReportes() {
        
        return ventanaReportes;
    }

    /**
     * @param ventanaProveedores the ventanaProveedores to set
     */
    public void setVentanaReportes(VentanaReportes ventanaReportes) {
        this.ventanaReportes = ventanaReportes;
    }

    /**
     * @return the contenidoTablaProveedores
     */
    public DefaultTableModel getContenidoTablaReporte() {
        return contenidoTablaReporte;
    }

    /**
     * @param contenidoTablaProveedores the contenidoTablaProveedores to set
     */
    public void setContenidoTablaReporte(DefaultTableModel contenidoTablaReporte) {
        this.contenidoTablaReporte = contenidoTablaReporte;
    }


    /**
     * @return the etiquetaProveedores
     */
    public javax.swing.JLabel getTituloReporte() {
        return tituloReporte;
    }

    /**
     * @param etiquetaProveedores the etiquetaProveedores to set
     */
    public void setTituloReporte(javax.swing.JLabel tituloReporte) {
        this.tituloReporte = tituloReporte;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public javax.swing.JTable getTablaReporte() {
        return tablaReporte;
    }

    
    public void setTablaReporte(javax.swing.JTable tablaReporte) {
        this.tablaReporte = tablaReporte;
    }
}
